// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/schedules": {
    params: {};
  };
  "/schedules/new": {
    params: {};
  };
  "/schedules/:id": {
    params: {
      "id": string;
    };
  };
  "/schedules/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/approvals": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/set-language": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/schedules" | "/schedules/new" | "/schedules/:id" | "/schedules/:id/edit" | "/approvals" | "/notifications" | "/set-language";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/schedules.tsx": {
    id: "routes/schedules";
    page: "/schedules";
  };
  "routes/schedules.new.tsx": {
    id: "routes/schedules.new";
    page: "/schedules/new";
  };
  "routes/schedules.$id.tsx": {
    id: "routes/schedules.$id";
    page: "/schedules/:id";
  };
  "routes/schedules.$id_.edit.tsx": {
    id: "routes/schedules.$id_.edit";
    page: "/schedules/:id/edit";
  };
  "routes/approvals.tsx": {
    id: "routes/approvals";
    page: "/approvals";
  };
  "routes/notifications.tsx": {
    id: "routes/notifications";
    page: "/notifications";
  };
  "routes/set-language.tsx": {
    id: "routes/set-language";
    page: "/set-language";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/schedules": typeof import("./app/routes/schedules.tsx");
  "routes/schedules.new": typeof import("./app/routes/schedules.new.tsx");
  "routes/schedules.$id": typeof import("./app/routes/schedules.$id.tsx");
  "routes/schedules.$id_.edit": typeof import("./app/routes/schedules.$id_.edit.tsx");
  "routes/approvals": typeof import("./app/routes/approvals.tsx");
  "routes/notifications": typeof import("./app/routes/notifications.tsx");
  "routes/set-language": typeof import("./app/routes/set-language.tsx");
};